name: CD - AdminService

on:
  push:
    branches:
      - main
    paths:
      - 'adminService/**'

jobs:
  docker-push:
    uses: ./.github/workflows/_docker-build-push.yml
    with:
      service_name: admin-service
      directory: adminService
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
