name: CD - ApiGateway

on:
  push:
    branches:
      - main
    paths:
      - 'ApiGatewaySmartSure/**'

jobs:
  docker-push:
    uses: ./.github/workflows/_docker-build-push.yml
    with:
      service_name: api-gateway
      directory: ApiGatewaySmartSure
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
