name: CD - ClaimService

on:
  push:
    branches:
      - main
    paths:
      - 'claimService/**'

jobs:
  docker-push:
    uses: ./.github/workflows/_docker-build-push.yml
    with:
      service_name: claim-service
      directory: claimService
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
