name: CD - ConfigServer

on:
  push:
    branches:
      - main
    paths:
      - 'config-server-smart-sure/**'

jobs:
  docker-push:
    uses: ./.github/workflows/_docker-build-push.yml
    with:
      service_name: config-server
      directory: config-server-smart-sure
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
