name: CD - PolicyService

on:
  push:
    branches:
      - main
    paths:
      - 'PolicyService/**'

jobs:
  docker-push:
    uses: ./.github/workflows/_docker-build-push.yml
    with:
      service_name: policy-service
      directory: PolicyService
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
